CREATE OR REPLACE TRIGGER TR_CHECK_SALARY
BEFORE INSERT OR UPDATE ON EMP
FOR EACH ROW
BEGIN
    IF :NEW.SAL > 50000 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Transaction rejected: Salary cannot exceed Rs. 50,000.');
    END IF;
END;
/
